apiVersion: apps/v1
kind: Deployment
metadata:
  name: newman-www-deployment
  labels:
    app.kubernetes.io/name: newman-www
    app.kubernetes.io/instance: newman-www-v1
    app.kubernetes.io/component: frontend
    app: newman-www
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: newman-www
      app.kubernetes.io/instance: newman-www-v1
      app.kubernetes.io/component: frontend
      app: newman-www
  template:
    metadata:
      labels:
        app.kubernetes.io/name: newman-www
        app.kubernetes.io/instance: newman-www-v1
        app.kubernetes.io/component: frontend
        app: newman-www
    spec:
      containers:
      - name: newman-www
        image: registry.digitalocean.com/pjh/newman-www@sha256:db6ea96d35530bf20947f30af233c5601ad67d528677692a5c3a7c3567b774cf
        ports:
        - containerPort: 3000

